//! Refusal engine port definition
//!
//! Trait for generating cryptographic refusal receipts when packets
//! are inadmissible-before (no negotiation, no discretionary bypass).

use async_trait::async_trait;

use crate::domain::{AuthErrorCode, RefusalReason, RefusalReceipt, TypeCheckErrorCode, WipError};

/// Refusal engine for generating inadmissible-before receipts
///
/// Issues cryptographic receipts proving packet rejection due to:
/// - WIP capacity exceeded
/// - Authentication failure
/// - H-guard violation
/// - Type check failure
///
/// All refusals are inadmissible-before (no negotiation, no discretionary bypass).
#[async_trait]
pub trait RefusalEngine: Send + Sync {
    /// Issue a refusal receipt for WIP capacity exceeded
    ///
    /// # Arguments
    /// * `packet_id` - Identifier of the rejected packet
    /// * `current` - Current WIP count
    /// * `limit` - WIP limit
    ///
    /// # Returns
    /// Cryptographic receipt proving the refusal
    async fn refuse_wip_exceeded(
        &self,
        packet_id: &str,
        current: usize,
        limit: usize,
    ) -> RefusalReceipt;

    /// Issue a refusal receipt for authentication failure
    ///
    /// # Arguments
    /// * `packet_id` - Identifier of the rejected packet
    /// * `error_code` - Specific authentication error code
    /// * `message` - Human-readable error message
    ///
    /// # Returns
    /// Cryptographic receipt proving the refusal
    async fn refuse_auth_failed(
        &self,
        packet_id: &str,
        error_code: AuthErrorCode,
        message: &str,
    ) -> RefusalReceipt;

    /// Issue a refusal receipt for H-guard violation
    ///
    /// # Arguments
    /// * `packet_id` - Identifier of the rejected packet
    /// * `guard_id` - Identifier of the violated guard
    /// * `condition` - Guard condition that was violated
    /// * `message` - Human-readable error message
    ///
    /// # Returns
    /// Cryptographic receipt proving the refusal
    async fn refuse_guard_failed(
        &self,
        packet_id: &str,
        guard_id: &str,
        condition: &str,
        message: &str,
    ) -> RefusalReceipt;

    /// Issue a refusal receipt for type check failure
    ///
    /// # Arguments
    /// * `packet_id` - Identifier of the rejected packet
    /// * `error_code` - Specific type check error code
    /// * `attempted_type` - The packet type that was attempted
    /// * `message` - Human-readable error message
    ///
    /// # Returns
    /// Cryptographic receipt proving the refusal
    async fn refuse_type_check_failed(
        &self,
        packet_id: &str,
        error_code: TypeCheckErrorCode,
        attempted_type: &str,
        message: &str,
    ) -> RefusalReceipt;

    /// Issue a refusal receipt for type check failure with validation errors
    ///
    /// # Arguments
    /// * `packet_id` - Identifier of the rejected packet
    /// * `error_code` - Specific type check error code
    /// * `attempted_type` - The packet type that was attempted
    /// * `message` - Human-readable error message
    /// * `errors` - List of validation errors
    ///
    /// # Returns
    /// Cryptographic receipt proving the refusal
    async fn refuse_type_check_failed_with_errors(
        &self,
        packet_id: &str,
        error_code: TypeCheckErrorCode,
        attempted_type: &str,
        message: &str,
        errors: Vec<String>,
    ) -> RefusalReceipt;

    /// Issue a refusal receipt from a WIP error
    ///
    /// Convenience method for converting WipError to RefusalReceipt.
    ///
    /// # Arguments
    /// * `packet_id` - Identifier of the rejected packet
    /// * `error` - The WIP error that occurred
    ///
    /// # Returns
    /// Cryptographic receipt proving the refusal
    async fn refuse_from_wip_error(&self, packet_id: &str, error: &WipError) -> RefusalReceipt {
        match error {
            WipError::WipLimitReached { current, limit } => {
                self.refuse_wip_exceeded(packet_id, *current, *limit).await
            }
            WipError::GateClosed => {
                self.refuse_auth_failed(
                    packet_id,
                    AuthErrorCode::InsufficientPermissions,
                    "WIP gate is closed",
                )
                .await
            }
            WipError::ExecutionFailed(msg) | WipError::ConfigurationError(msg) => {
                self.refuse_auth_failed(packet_id, AuthErrorCode::InsufficientPermissions, msg)
                    .await
            }
        }
    }

    /// Get the issuer identity for receipts generated by this engine
    fn issuer(&self) -> &str;
}
